### ISSUE TITLE
Problem with SQL init

### ISSUE THREAD

**Issue by jusabatier** [sigrennesmetropole/geor_signalement#27]
Hi,

I'm trying to install this tool, but I think there is some problem with https://github.com/sigrennesmetropole/geor_signalement/blob/master/resources/sql/signalement-initialisation.sql : 

The mentioned shema 'geor_gaspar' doesn't exists. Shouldn't it be 'signalement' instead ?

**Comment by ThomasBruleOpen** [comment]
Hi, 

Sorry, you wrote this issue a long time ago ... 

You're right : there is a mistake in the initialisation file. Have to correct this next version.
