### ISSUE TITLE
[bug report] signalement-mapstore-addon - problem with components positions after sending a report (signalement)

### ISSUE THREAD

**Issue by rgoffinet** [sigrennesmetropole/geor_signalement#43]
**Description**
When using georchestra-signalement-mapstore-addon, after sending a report (signalement), the positioning of mapstore's components is not correctly handled after the automatic closing of the addon window.

**To reproduce**
1. open the "signalement" addon
2. generate a report (signalement) and send it
3. when the addon window is closing, the search bar and the bottom right-hand navbar remain blocked on the map and aren't positioning back to the right-hand side of the application.
This is even more annoying when using an MS context using georchestra-signalement-mapstore-management-addon, as the search bar is then placed behind the signalement-management-tool window.

**Expected behavior**
After the automatic closing of the addon window, mapstore's components (nav bar and search bar) are correctly positionned on the right-hand side of the application.

**Screenshot**
![image](https://github.com/sigrennesmetropole/geor_signalement/assets/136472866/ee182734-a5f4-4ea6-8733-3ca2c1422c34)

**Desktop**
Browser : firefox 102.14 (32bits) ; chrome 116.0.5845 (64 bits) ; Edge 115.0.1901 (64 bits)
Version MapStore : 2022.02.02 & 2023.02 RC2

**Comment by rgoffinet** [comment]
the problem still exists with v1.12.4 of signalement and the icon of the plugin remains highlighted as shown below : 

![image](https://github.com/sigrennesmetropole/geor_signalement/assets/136472866/9ae07564-f7fd-4312-b670-af01277ea3b6)

**Comment by noeandrian** [comment]
issue solved by version v1.12.6
